siteTitle="The Pokemon Go Guide"
siteDescription="The comprehensive how-to guide for playing the iPhone and Android app game Pokemon Go."
baseColor = "#24CCAA"
linkPrefix = "/"
siteBaseUrl = "http://pokemongoguide.us"
docPages = [
  "/",
  "/getting-started/",
  "/how-to-catch-pokemon/",
  "/how-to-track-pokemon/",
  "/how-to-train-pokemon/",
]
